# Generated by Django 5.1.7 on 2026-03-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('canteen_owner', 'Canteen Owner'), ('xerox_owner', 'Xerox Shop Owner'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
